feat: add functionality for read document function
yogeshhk/MiningResume pull request #41
Opened 2024-10-07 06:16 UTC by Abhinav-Anil

1.  read_document function was not callable in the main.py
2. added the read_document functionality in the parser_by_regex.py script
3.  PdfReader has been used for reading the file and then for extraction of it.

2024-10-08 01:52 UTC, yogeshhk commented
@Abhinav-Anil can you see similar pdf reading functionality in `src/file_operations.py`? can that be used by adjustment?

2024-10-08 03:40 UTC, Abhinav-Anil commented
> @Abhinav-Anil can you see similar pdf reading functionality in `src/file_operations.py`? can that be used by adjustment?

Yes, that can be used. I'll adjust and raise the PR again.

2024-11-07 02:42 UTC, yogeshhk requested changes
Can reuse the existing function

2024-11-07 02:44 UTC, yogeshhk commented
@Abhinav-Anil I will not merge the current PR then, as you are planning to submit the updated code. Rejecting this PR for now.

2024-11-07 02:44 UTC, closed without merging